### ISSUE TITLE
depmap download error

### ISSUE THREAD

**Issue by pyeguy** [GilbertLabUCSF/CanDI#30]
getting the following error on an install

```python
~/dev via 🅒 candi
🐙 ❯ python CanDI/CanDI/setup/install.py
Getting download information from DepMap
GET Successful
Writing config file
Traceback (most recent call last):
  File "/Users/cameronpye/dev/CanDI/CanDI/setup/install.py", line 8, in <module>
    m.download_defaults()
  File "/Users/cameronpye/dev/CanDI/CanDI/setup/manager.py", line 130, in download_defaults
    entries = [self.manage_request(i, "depmap") for i in to_download]
  File "/Users/cameronpye/dev/CanDI/CanDI/setup/manager.py", line 130, in <listcomp>
    entries = [self.manage_request(i, "depmap") for i in to_download]
  File "/Users/cameronpye/dev/CanDI/CanDI/setup/manager.py", line 139, in manage_request
    filename = self.parser['depmap_files'][name]
  File "/opt/homebrew/Caskroom/miniconda/base/envs/candi/lib/python3.10/configparser.py", line 1258, in __getitem__
    raise KeyError(key)
KeyError: 'sample_info'
```

**Comment by abearab** [comment]
CanDI is trying to use most updated version of DepMap. It seems they have changed several table formats, etc. So CanDI fails to deal with that and I need some time to fix it.

https://github.com/broadinstitute/depmap_omics/releases/tag/22Q4

**Comment by abearab** [comment]
In the meanwhile, I can share a `.zip` file from including CanDI installed with previous versions of DepMap; so you can start using CanDI's functionalities. Let me know if you want me to share that with you.

**Comment by abearab** [comment]
Covered in #34
