### ISSUE TITLE
Add comments - docstrings format

### ISSUE THREAD

**Issue by Yogiski** [GilbertLabUCSF/CanDI#9]
Little to know in-code comments explaining functions

**Comment by abearab** [comment]
@Yogiski, below is the Sphinx docstring format. Can you review your comment in this format, please? Let me know how can I help. 

https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

```
The Sphinx docstring format
In general, a typical Sphinx docstring has the following format:

"""[Summary]

:param [ParamName]: [ParamDescription], defaults to [DefaultParamVal]
:type [ParamName]: [ParamType](, optional)
...
:raises [ErrorType]: [ErrorDescription]
...
:return: [ReturnDescription]
:rtype: [ReturnType]
"""
```

**Comment by abearab** [comment]
For some reason, I can not capture docstring contents in ReadTheDocs although it works fine locally (local HTML file). This is what I can see in log file from ReadTheDocs's run:

```
WARNING: autodoc: failed to import module 'candi' from module 'CanDI'; the following exception was raised:
Traceback (most recent call last):
  File "CanDI/data.py", line 68, in _init_index_tables
    assert os.path.exists(new_path)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/candi/conda/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 66, in import_module
    return importlib.import_module(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/candi/conda/docs/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/candi/checkouts/docs/CanDI/__init__.py", line 2, in <module>
    data = data.Data() #Global object data instantiated on import required for access by GeneQuery Objects
  File "/home/docs/checkouts/readthedocs.org/user_builds/candi/checkouts/docs/CanDI/data.py", line 29, in __init__
    self._init_index_tables()
  File "/home/docs/checkouts/readthedocs.org/user_builds/candi/checkouts/docs/CanDI/data.py", line 71, in _init_index_tables
    raise(RuntimeError, "You are missing essential index table: {}. exiting...".format(new_path))
TypeError: exceptions must derive from BaseException
```

I think [this line](https://github.com/GilbertLabUCSF/CanDI/blob/f48581181d43c468738b10f27e9fd2eebbc50e9b/CanDI/data.py#L73) fails 

> An AssertionError can only occur when an assert statement fails. 
[Source link](https://airbrake.io/blog/python/python-assertionerror) 

I'm not sure what we can do to deal with this!

**Comment by abearab** [comment]
@Yogiski this is also well done!
